### ISSUE TITLE
Ajouter des scénarios au campagne

### ISSUE THREAD

**Issue by Heelis** [Aendawyn/kiwi#1]

**Comment by Aendawyn** [comment]
Le développement est en cours. Ce sera possible à base de drag & drop de la liste de tous les scénarios vers la liste des scénarios de la campagne.

Les scénarios d'une campagne pourront également être ordonnées par drag & drop.

**Comment by Aendawyn** [comment]
Le commit 01908a1a9dd4901097f2719d3bd67d63eb68f939 ajoute l'ajout/le retrait de scénarios aux campagnes. Elles sont persistées comme n'importe quel autre modèle. 

Il manque maintenant la possibilité de lancer les campagnes.

**Comment by Aendawyn** [comment]
Le commit 86c848764d571e89d2b5473f32dc3990c50859bd permet de lancer des campagnes depuis la vue Campagnes.

J'attend vos retours!
