### ISSUE TITLE
Afficher étiquette de scenario dans editeur de campagne

### ISSUE THREAD

**Issue by Heelis** [Aendawyn/kiwi#5]
En tant que développeur de campagne de test
Je souhaite pouvoir différencier des scénarios du même nom mais avec des étiquettes différente dans l'écran d'édition de campagne
afin de pouvoir différencier des scenarios du même nom.

Critere d'acceptence
Lorsqu'on double clique sur une campagne pour l'éditer, l'étiquette du scenario s'affiche à coté du libellé

**Comment by Aendawyn** [comment]
Je vous propose d'afficher l'étiquette colorée, en plus petit, en dessous du nom de la story dans la liste des scénarios disponibles / de la campagne. 

Cela conviendrait-il ?

**Comment by Heelis** [comment]
Oui, très bien

**Comment by Aendawyn** [comment]
Disponible depuis le commit 256a912ac4e61392369c12a2cdfb1183352125bb.
Je clos l'issue. Si le résultat ne vous convient pas, n'hésitez pas à la réouvrir 😸 

![kiwi_etiquette_scenarios_campagne](https://user-images.githubusercontent.com/2827169/37875666-f3d5111e-3042-11e8-9ec9-485fd232ce59.png)
