### ISSUE TITLE
Ajout d'un test case killer

### ISSUE THREAD

**Issue by tchignard** [Aendawyn/kiwi#8]
En tant qu'utilisateur kiwi
Je souhaite pouvoir insérer dans une campagne, un scénario killer (système) qui fermerait proprement l'application en cours de test
Afin de démarrer mon prochain scénario ou ma nouvelle campagne de test sans impact avec le précedent jeu

Critère acceptation

- [ ] Ajouter dans la liste des cas, un scénario système

- [ ] Avoir la possibilité de l'insérer dans les campagnes

**Comment by Aendawyn** [comment]
Cela existe plus ou moins, en fait ça a été pensé autrement.

D'un côté on avait les scénarios, qui sont des étapes de tests plus ou moins autonome (cela dépend de la volonté du testeur).
De l'autre, on a les campagnes, qui exécutent des scénarios dans un certain ordre.

**Ce qui avait été pensé:** 

Pour exécuter une campagne, il faut utiliser un launcher spéciale, qui fait une RAZ de l'appli. Sachant qu'entre chaque scénario de la même campagne l'appli n'est pas relancée, les scénarios évolueraient dans le même contexte. 
Par contre, entre chaque campagne, l'appli est tuée, et le launcher utilisé remet à zéro l'appli pour que la campagne se déroule bien

Kiwi a déjà la possibilité d'ajouter des étapes qui ne sont pas des mouvements de souris ou clavier: l'API est pensée pour ajouter des steps bien particulière: "prend un screenshot intermédiaire", "redémarre l'appli", "attend 1 minute", ... Elles n'existent pas encore mais l'API le permet. 

je pense que ton cas d'utilisation est couvert par les launchers; mais si ce n'est pas le cas, on peut voir pour intégrer cela comme étant une étape spéciale d'un scénario spécial.

**Comment by tchignard** [comment]
Ok, si les campagnes sont indépendantes, ça me va, j'avais pas fais attention.
Oui pour le moment, ça irait avec les launchers et effectivement, de mon coté, j'opterai que pour la mise en place de scénarios de bout en bout (et non des campagnes de bout en bout)
